-- Knowledge Center LMS - Complete Database Schema
-- Creates all tables with proper structure for Kenya insurance/banking software training
-- UUIDs are automatically generated by MySQL using DEFAULT (uuid())

-- ============================================
-- AUTHENTICATION & AUTHORIZATION
-- ===========================================

-- Roles Table (UUID IDs)
CREATE TABLE IF NOT EXISTS roles (
  id CHAR(36) NOT NULL DEFAULT (uuid()) PRIMARY KEY,
  name VARCHAR(50) UNIQUE NOT NULL,
  display_name VARCHAR(100) NOT NULL,
  description TEXT,
  is_system_role BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Users Table (UUID IDs)
CREATE TABLE IF NOT EXISTS users (
  id CHAR(36) NOT NULL DEFAULT (uuid()) PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  name VARCHAR(255),
  role_id CHAR(36),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_email (email),
  INDEX idx_role_id (role_id),
  FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- OTP Codes Table (UUID IDs)
CREATE TABLE IF NOT EXISTS otp_codes (
  id CHAR(36) NOT NULL DEFAULT (uuid()) PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  code VARCHAR(6) NOT NULL,
  expires_at TIMESTAMP NOT NULL,
  used BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_email (email),
  INDEX idx_code (code),
  INDEX idx_expires_at (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Password Resets Table (UUID IDs)
CREATE TABLE IF NOT EXISTS password_resets (
  id CHAR(36) NOT NULL DEFAULT (uuid()) PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  token VARCHAR(255) NOT NULL,
  expires_at TIMESTAMP NOT NULL,
  used BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_email (email),
  INDEX idx_token (token),
  INDEX idx_expires_at (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Note: Default roles are inserted in sample data migration (003_sample_data.sql)

-- ============================================
-- ORGANIZATIONAL STRUCTURE (UUID IDs)
-- ===========================================

-- Departments Table
CREATE TABLE IF NOT EXISTS departments (
  id CHAR(36) NOT NULL DEFAULT (uuid()) PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  description TEXT,
  parent_id CHAR(36),
  manager_id CHAR(36),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_parent (parent_id),
  INDEX idx_manager (manager_id),
  FOREIGN KEY (parent_id) REFERENCES departments(id) ON DELETE SET NULL,
  FOREIGN KEY (manager_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- User Departments (Many-to-Many)
CREATE TABLE IF NOT EXISTS user_departments (
  user_id CHAR(36),
  department_id CHAR(36),
  role VARCHAR(50) DEFAULT 'member',
  joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, department_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- User Groups
CREATE TABLE IF NOT EXISTS user_groups (
  id CHAR(36) NOT NULL DEFAULT (uuid()) PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  description TEXT,
  created_by CHAR(36),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_created_by (created_by),
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- User Group Members
CREATE TABLE IF NOT EXISTS user_group_members (
  user_id CHAR(36),
  group_id CHAR(36),
  joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, group_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (group_id) REFERENCES user_groups(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================
-- CONTENT MANAGEMENT (UUID IDs)
-- ============================================

-- Categories
CREATE TABLE IF NOT EXISTS categories (
  id CHAR(36) NOT NULL DEFAULT (uuid()) PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  slug VARCHAR(100) UNIQUE NOT NULL,
  description TEXT,
  parent_id CHAR(36),
  icon VARCHAR(50),
  color VARCHAR(7),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_slug (slug),
  INDEX idx_parent (parent_id),
  FOREIGN KEY (parent_id) REFERENCES categories(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tags
CREATE TABLE IF NOT EXISTS tags (
  id CHAR(36) NOT NULL DEFAULT (uuid()) PRIMARY KEY,
  name VARCHAR(50) UNIQUE NOT NULL,
  slug VARCHAR(50) UNIQUE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_slug (slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Courses
CREATE TABLE IF NOT EXISTS courses (
  id CHAR(36) NOT NULL DEFAULT (uuid()) PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  slug VARCHAR(255) UNIQUE NOT NULL,
  description TEXT,
  short_description VARCHAR(500),
  category_id CHAR(36),
  instructor_id CHAR(36),
  thumbnail_url VARCHAR(500),
  status ENUM('draft', 'published', 'archived') DEFAULT 'draft',
  difficulty_level ENUM('beginner', 'intermediate', 'advanced') DEFAULT 'beginner',
  duration_minutes INT DEFAULT 0,
  price DECIMAL(10,2) DEFAULT 0.00,
  currency VARCHAR(3) DEFAULT 'KES',
  language VARCHAR(10) DEFAULT 'en',
  is_featured BOOLEAN DEFAULT FALSE,
  enrollment_count INT DEFAULT 0,
  rating DECIMAL(3,2) DEFAULT 0.00,
  total_ratings INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_slug (slug),
  INDEX idx_category (category_id),
  INDEX idx_instructor (instructor_id),
  INDEX idx_status (status),
  FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL,
  FOREIGN KEY (instructor_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Course Tags (Many-to-Many)
CREATE TABLE IF NOT EXISTS course_tags (
  course_id CHAR(36),
  tag_id CHAR(36),
  PRIMARY KEY (course_id, tag_id),
  FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE,
  FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Modules
CREATE TABLE IF NOT EXISTS modules (
  id CHAR(36) NOT NULL DEFAULT (uuid()) PRIMARY KEY,
  course_id CHAR(36) NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  order_index INT DEFAULT 0,
  is_required BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_course (course_id),
  INDEX idx_order (course_id, order_index),
  FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Lessons
CREATE TABLE IF NOT EXISTS lessons (
  id CHAR(36) NOT NULL DEFAULT (uuid()) PRIMARY KEY,
  module_id CHAR(36) NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  content_type ENUM('video', 'text', 'document', 'quiz', 'assignment', 'live_session') DEFAULT 'text',
  content_url VARCHAR(500),
  content_text LONGTEXT,
  duration_minutes INT DEFAULT 0,
  order_index INT DEFAULT 0,
  is_required BOOLEAN DEFAULT TRUE,
  is_preview BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_module (module_id),
  INDEX idx_order (module_id, order_index),
  FOREIGN KEY (module_id) REFERENCES modules(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Content Library
CREATE TABLE IF NOT EXISTS content_library (
  id CHAR(36) NOT NULL DEFAULT (uuid()) PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  file_name VARCHAR(255) NOT NULL,
  file_path VARCHAR(500) NOT NULL,
  file_type VARCHAR(50),
  file_size BIGINT,
  mime_type VARCHAR(100),
  uploaded_by CHAR(36) NOT NULL,
  category_id CHAR(36),
  is_public BOOLEAN DEFAULT FALSE,
  download_count INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_uploaded_by (uploaded_by),
  INDEX idx_category (category_id),
  FOREIGN KEY (uploaded_by) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================
-- LEARNING & ENROLLMENTS (UUID IDs)
-- ============================================

-- Enrollments
CREATE TABLE IF NOT EXISTS enrollments (
  id CHAR(36) NOT NULL DEFAULT (uuid()) PRIMARY KEY,
  user_id CHAR(36) NOT NULL,
  course_id CHAR(36) NOT NULL,
  status ENUM('enrolled', 'in_progress', 'completed', 'dropped') DEFAULT 'enrolled',
  progress_percentage DECIMAL(5,2) DEFAULT 0.00,
  enrolled_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  started_at TIMESTAMP NULL,
  completed_at TIMESTAMP NULL,
  last_accessed_at TIMESTAMP NULL,
  UNIQUE KEY unique_enrollment (user_id, course_id),
  INDEX idx_user (user_id),
  INDEX idx_course (course_id),
  INDEX idx_status (status),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Lesson Progress
CREATE TABLE IF NOT EXISTS lesson_progress (
  id CHAR(36) NOT NULL DEFAULT (uuid()) PRIMARY KEY,
  enrollment_id CHAR(36) NOT NULL,
  lesson_id CHAR(36) NOT NULL,
  status ENUM('not_started', 'in_progress', 'completed') DEFAULT 'not_started',
  progress_percentage DECIMAL(5,2) DEFAULT 0.00,
  time_spent_minutes INT DEFAULT 0,
  last_position INT DEFAULT 0,
  completed_at TIMESTAMP NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY unique_progress (enrollment_id, lesson_id),
  INDEX idx_enrollment (enrollment_id),
  INDEX idx_lesson (lesson_id),
  FOREIGN KEY (enrollment_id) REFERENCES enrollments(id) ON DELETE CASCADE,
  FOREIGN KEY (lesson_id) REFERENCES lessons(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Learning Paths
CREATE TABLE IF NOT EXISTS learning_paths (
  id CHAR(36) NOT NULL DEFAULT (uuid()) PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  category_id CHAR(36),
  thumbnail_url VARCHAR(500),
  status ENUM('draft', 'published', 'archived') DEFAULT 'draft',
  is_featured BOOLEAN DEFAULT FALSE,
  estimated_duration_hours INT DEFAULT 0,
  created_by CHAR(36),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_category (category_id),
  INDEX idx_status (status),
  FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL,
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Learning Path Courses
CREATE TABLE IF NOT EXISTS learning_path_courses (
  learning_path_id CHAR(36),
  course_id CHAR(36),
  order_index INT DEFAULT 0,
  is_required BOOLEAN DEFAULT TRUE,
  PRIMARY KEY (learning_path_id, course_id),
  INDEX idx_order (learning_path_id, order_index),
  FOREIGN KEY (learning_path_id) REFERENCES learning_paths(id) ON DELETE CASCADE,
  FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Learning Path Enrollments
CREATE TABLE IF NOT EXISTS learning_path_enrollments (
  id CHAR(36) NOT NULL DEFAULT (uuid()) PRIMARY KEY,
  user_id CHAR(36) NOT NULL,
  learning_path_id CHAR(36) NOT NULL,
  status ENUM('enrolled', 'in_progress', 'completed', 'dropped') DEFAULT 'enrolled',
  progress_percentage DECIMAL(5,2) DEFAULT 0.00,
  enrolled_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  completed_at TIMESTAMP NULL,
  UNIQUE KEY unique_path_enrollment (user_id, learning_path_id),
  INDEX idx_user (user_id),
  INDEX idx_path (learning_path_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (learning_path_id) REFERENCES learning_paths(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================
-- ASSESSMENTS & QUIZZES (UUID IDs)
-- ============================================

-- Assessments
CREATE TABLE IF NOT EXISTS assessments (
  id CHAR(36) NOT NULL DEFAULT (uuid()) PRIMARY KEY,
  course_id CHAR(36),
  lesson_id CHAR(36),
  title VARCHAR(255) NOT NULL,
  description TEXT,
  type ENUM('quiz', 'exam', 'assignment') DEFAULT 'quiz',
  passing_score DECIMAL(5,2) DEFAULT 70.00,
  time_limit_minutes INT NULL,
  max_attempts INT DEFAULT 1,
  is_required BOOLEAN DEFAULT TRUE,
  randomize_questions BOOLEAN DEFAULT FALSE,
  show_results BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_course (course_id),
  INDEX idx_lesson (lesson_id),
  FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE,
  FOREIGN KEY (lesson_id) REFERENCES lessons(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Assessment Questions
CREATE TABLE IF NOT EXISTS assessment_questions (
  id CHAR(36) NOT NULL DEFAULT (uuid()) PRIMARY KEY,
  assessment_id CHAR(36) NOT NULL,
  question_text TEXT NOT NULL,
  question_type ENUM('multiple_choice', 'true_false', 'short_answer', 'essay') DEFAULT 'multiple_choice',
  options JSON,
  correct_answer TEXT,
  points DECIMAL(5,2) DEFAULT 1.00,
  order_index INT DEFAULT 0,
  explanation TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_assessment (assessment_id),
  INDEX idx_order (assessment_id, order_index),
  FOREIGN KEY (assessment_id) REFERENCES assessments(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Assessment Attempts
CREATE TABLE IF NOT EXISTS assessment_attempts (
  id CHAR(36) NOT NULL DEFAULT (uuid()) PRIMARY KEY,
  enrollment_id CHAR(36) NOT NULL,
  assessment_id CHAR(36) NOT NULL,
  score DECIMAL(5,2) DEFAULT 0.00,
  percentage DECIMAL(5,2) DEFAULT 0.00,
  passed BOOLEAN DEFAULT FALSE,
  time_taken_minutes INT DEFAULT 0,
  started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  submitted_at TIMESTAMP NULL,
  INDEX idx_enrollment (enrollment_id),
  INDEX idx_assessment (assessment_id),
  FOREIGN KEY (enrollment_id) REFERENCES enrollments(id) ON DELETE CASCADE,
  FOREIGN KEY (assessment_id) REFERENCES assessments(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Assessment Answers
CREATE TABLE IF NOT EXISTS assessment_answers (
  id CHAR(36) NOT NULL DEFAULT (uuid()) PRIMARY KEY,
  attempt_id CHAR(36) NOT NULL,
  question_id CHAR(36) NOT NULL,
  answer_text TEXT,
  is_correct BOOLEAN DEFAULT FALSE,
  points_earned DECIMAL(5,2) DEFAULT 0.00,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_attempt (attempt_id),
  INDEX idx_question (question_id),
  FOREIGN KEY (attempt_id) REFERENCES assessment_attempts(id) ON DELETE CASCADE,
  FOREIGN KEY (question_id) REFERENCES assessment_questions(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================
-- CERTIFICATES & COMPLIANCE (UUID IDs)
-- ============================================

-- Certificates
CREATE TABLE IF NOT EXISTS certificates (
  id CHAR(36) NOT NULL DEFAULT (uuid()) PRIMARY KEY,
  user_id CHAR(36) NOT NULL,
  course_id CHAR(36),
  learning_path_id CHAR(36),
  certificate_number VARCHAR(100) UNIQUE NOT NULL,
  issued_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  expires_at TIMESTAMP NULL,
  pdf_url VARCHAR(500),
  INDEX idx_user (user_id),
  INDEX idx_course (course_id),
  INDEX idx_path (learning_path_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE SET NULL,
  FOREIGN KEY (learning_path_id) REFERENCES learning_paths(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Compliance Requirements
CREATE TABLE IF NOT EXISTS compliance_requirements (
  id CHAR(36) NOT NULL DEFAULT (uuid()) PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  course_id CHAR(36),
  learning_path_id CHAR(36),
  department_id CHAR(36),
  user_group_id CHAR(36),
  required_for ENUM('all', 'department', 'group', 'role', 'individual') DEFAULT 'all',
  deadline_days INT DEFAULT 90,
  is_mandatory BOOLEAN DEFAULT TRUE,
  priority ENUM('low', 'medium', 'high', 'critical') DEFAULT 'medium',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_course (course_id),
  INDEX idx_path (learning_path_id),
  INDEX idx_department (department_id),
  INDEX idx_group (user_group_id),
  FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE,
  FOREIGN KEY (learning_path_id) REFERENCES learning_paths(id) ON DELETE CASCADE,
  FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE CASCADE,
  FOREIGN KEY (user_group_id) REFERENCES user_groups(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================
-- NOTIFICATIONS & COMMUNICATION (UUID IDs)
-- ============================================

-- Notifications
CREATE TABLE IF NOT EXISTS notifications (
  id CHAR(36) NOT NULL DEFAULT (uuid()) PRIMARY KEY,
  user_id CHAR(36) NOT NULL,
  title VARCHAR(255) NOT NULL,
  message TEXT,
  type ENUM('info', 'success', 'warning', 'error', 'course', 'assignment', 'deadline') DEFAULT 'info',
  is_read BOOLEAN DEFAULT FALSE,
  link_url VARCHAR(500),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_user (user_id),
  INDEX idx_read (user_id, is_read),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Live Sessions
CREATE TABLE IF NOT EXISTS live_sessions (
  id CHAR(36) NOT NULL DEFAULT (uuid()) PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  instructor_id CHAR(36) NOT NULL,
  platform ENUM('zoom', 'teams', 'google_meet', 'custom') DEFAULT 'zoom',
  meeting_url VARCHAR(500),
  meeting_id VARCHAR(255),
  meeting_password VARCHAR(100),
  scheduled_at TIMESTAMP NOT NULL,
  duration_minutes INT DEFAULT 60,
  max_attendees INT,
  status ENUM('scheduled', 'live', 'completed', 'cancelled') DEFAULT 'scheduled',
  recording_url VARCHAR(500),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_instructor (instructor_id),
  INDEX idx_scheduled (scheduled_at),
  INDEX idx_status (status),
  FOREIGN KEY (instructor_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Live Session Attendees
CREATE TABLE IF NOT EXISTS live_session_attendees (
  session_id CHAR(36),
  user_id CHAR(36),
  status ENUM('registered', 'attended', 'absent') DEFAULT 'registered',
  registered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  attended_at TIMESTAMP NULL,
  PRIMARY KEY (session_id, user_id),
  FOREIGN KEY (session_id) REFERENCES live_sessions(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Discussions
CREATE TABLE IF NOT EXISTS discussions (
  id CHAR(36) NOT NULL DEFAULT (uuid()) PRIMARY KEY,
  course_id CHAR(36),
  title VARCHAR(255) NOT NULL,
  content TEXT,
  author_id CHAR(36) NOT NULL,
  is_pinned BOOLEAN DEFAULT FALSE,
  is_locked BOOLEAN DEFAULT FALSE,
  reply_count INT DEFAULT 0,
  view_count INT DEFAULT 0,
  last_reply_at TIMESTAMP NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_course (course_id),
  INDEX idx_author (author_id),
  INDEX idx_pinned (course_id, is_pinned, created_at),
  FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE,
  FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Discussion Replies
CREATE TABLE IF NOT EXISTS discussion_replies (
  id CHAR(36) NOT NULL DEFAULT (uuid()) PRIMARY KEY,
  discussion_id CHAR(36) NOT NULL,
  author_id CHAR(36) NOT NULL,
  content TEXT NOT NULL,
  parent_reply_id CHAR(36),
  is_approved BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_discussion (discussion_id),
  INDEX idx_author (author_id),
  INDEX idx_parent (parent_reply_id),
  FOREIGN KEY (discussion_id) REFERENCES discussions(id) ON DELETE CASCADE,
  FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (parent_reply_id) REFERENCES discussion_replies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================
-- GAMIFICATION (UUID IDs)
-- ============================================

-- Badges
CREATE TABLE IF NOT EXISTS badges (
  id CHAR(36) NOT NULL DEFAULT (uuid()) PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  description TEXT,
  icon_url VARCHAR(500),
  criteria TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- User Badges
CREATE TABLE IF NOT EXISTS user_badges (
  user_id CHAR(36),
  badge_id CHAR(36),
  earned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, badge_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (badge_id) REFERENCES badges(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- User Points
CREATE TABLE IF NOT EXISTS user_points (
  user_id CHAR(36) NOT NULL PRIMARY KEY,
  total_points INT DEFAULT 0,
  current_level INT DEFAULT 1,
  points_this_month INT DEFAULT 0,
  last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
