-- Sample Data for Knowledge Center LMS
-- Company: CAAVA Group - Software development for insurance and banking in Kenya
-- Uses Oracle products: Toad, WebLogic, JDeveloper, Oracle Database, Oracle Forms, etc.
-- UUIDs are automatically generated by MySQL using DEFAULT (uuid())
-- When inserting, simply omit the 'id' field and MySQL will generate it automatically

-- ============================================
-- ROLES (UUIDs auto-generated by MySQL)
-- ============================================

INSERT INTO roles (name, display_name, description, is_system_role) VALUES
('admin', 'Administrator', 'Full system access with all permissions', TRUE),
('learner', 'Learner', 'Standard user with access to learning content', TRUE),
('instructor', 'Instructor', 'Can create and manage courses', TRUE),
('auditor', 'Auditor', 'Read-only access for auditing purposes', TRUE),
('hr', 'HR Manager', 'Human resources and employee management', FALSE),
('developer', 'Developer', 'Software development team member', FALSE),
('qa', 'QA Engineer', 'Quality assurance and testing', FALSE),
('manager', 'Department Manager', 'Department head with team oversight', FALSE)
ON DUPLICATE KEY UPDATE name=name;

-- ============================================
-- SAMPLE USERS (UUIDs auto-generated by MySQL)
-- ============================================

-- Admin
INSERT INTO users (email, password, name, role_id)
SELECT 'admin@caavagroup.com', '$2a$10$rOzJqJqJqJqJqJqJqJqJeqJqJqJqJqJqJqJqJqJqJqJqJqJqJqJqJq', 'Admin User',
  (SELECT id FROM roles WHERE name = 'admin' LIMIT 1)
WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'admin@caavagroup.com');

-- Instructors
INSERT INTO users (email, password, name, role_id)
SELECT 'jane.mwangi@caavagroup.com', '$2a$10$rOzJqJqJqJqJqJqJqJqJeqJqJqJqJqJqJqJqJqJqJqJqJqJqJqJqJq', 'Jane Mwangi',
  (SELECT id FROM roles WHERE name = 'instructor' LIMIT 1)
WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'jane.mwangi@caavagroup.com');

INSERT INTO users (email, password, name, role_id)
SELECT 'david.ochieng@caavagroup.com', '$2a$10$rOzJqJqJqJqJqJqJqJqJeqJqJqJqJqJqJqJqJqJqJqJqJqJqJqJqJq', 'David Ochieng',
  (SELECT id FROM roles WHERE name = 'instructor' LIMIT 1)
WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'david.ochieng@caavagroup.com');

INSERT INTO users (email, password, name, role_id)
SELECT 'sarah.akinyi@caavagroup.com', '$2a$10$rOzJqJqJqJqJqJqJqJqJeqJqJqJqJqJqJqJqJqJqJqJqJqJqJqJqJq', 'Sarah Akinyi',
  (SELECT id FROM roles WHERE name = 'instructor' LIMIT 1)
WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'sarah.akinyi@caavagroup.com');

-- Developers
INSERT INTO users (email, password, name, role_id)
SELECT 'peter.otieno@caavagroup.com', '$2a$10$rOzJqJqJqJqJqJqJqJqJeqJqJqJqJqJqJqJqJqJqJqJqJqJqJqJqJq', 'Peter Otieno',
  (SELECT id FROM roles WHERE name = 'developer' LIMIT 1)
WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'peter.otieno@caavagroup.com');

INSERT INTO users (email, password, name, role_id)
SELECT 'james.kariuki@caavagroup.com', '$2a$10$rOzJqJqJqJqJqJqJqJqJeqJqJqJqJqJqJqJqJqJqJqJqJqJqJqJqJq', 'James Kariuki',
  (SELECT id FROM roles WHERE name = 'developer' LIMIT 1)
WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'james.kariuki@caavagroup.com');

-- Learners/Employees
INSERT INTO users (email, password, name, role_id)
SELECT 'john.kamau@caavagroup.com', '$2a$10$rOzJqJqJqJqJqJqJqJqJeqJqJqJqJqJqJqJqJqJqJqJqJqJqJqJqJq', 'John Kamau',
  (SELECT id FROM roles WHERE name = 'learner' LIMIT 1)
WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'john.kamau@caavagroup.com');

INSERT INTO users (email, password, name, role_id)
SELECT 'mary.wanjiku@caavagroup.com', '$2a$10$rOzJqJqJqJqJqJqJqJqJeqJqJqJqJqJqJqJqJqJqJqJqJqJqJqJqJq', 'Mary Wanjiku',
  (SELECT id FROM roles WHERE name = 'learner' LIMIT 1)
WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'mary.wanjiku@caavagroup.com');

INSERT INTO users (email, password, name, role_id)
SELECT 'grace.nyambura@caavagroup.com', '$2a$10$rOzJqJqJqJqJqJqJqJqJeqJqJqJqJqJqJqJqJqJqJqJqJqJqJqJqJq', 'Grace Nyambura',
  (SELECT id FROM roles WHERE name = 'learner' LIMIT 1)
WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'grace.nyambura@caavagroup.com');

INSERT INTO users (email, password, name, role_id)
SELECT 'brian.mutua@caavagroup.com', '$2a$10$rOzJqJqJqJqJqJqJqJqJeqJqJqJqJqJqJqJqJqJqJqJqJqJqJqJqJq', 'Brian Mutua',
  (SELECT id FROM roles WHERE name = 'learner' LIMIT 1)
WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'brian.mutua@caavagroup.com');

INSERT INTO users (email, password, name, role_id)
SELECT 'linda.chebet@caavagroup.com', '$2a$10$rOzJqJqJqJqJqJqJqJqJeqJqJqJqJqJqJqJqJqJqJqJqJqJqJqJqJq', 'Linda Chebet',
  (SELECT id FROM roles WHERE name = 'learner' LIMIT 1)
WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'linda.chebet@caavagroup.com');

INSERT INTO users (email, password, name, role_id)
SELECT 'daniel.mwangi@caavagroup.com', '$2a$10$rOzJqJqJqJqJqJqJqJqJeqJqJqJqJqJqJqJqJqJqJqJqJqJqJqJqJq', 'Daniel Mwangi',
  (SELECT id FROM roles WHERE name = 'learner' LIMIT 1)
WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'daniel.mwangi@caavagroup.com');

-- Managers
INSERT INTO users (email, password, name, role_id)
SELECT 'michelle.ndungu@caavagroup.com', '$2a$10$rOzJqJqJqJqJqJqJqJqJeqJqJqJqJqJqJqJqJqJqJqJqJqJqJqJqJq', 'Michelle Ndungu',
  (SELECT id FROM roles WHERE name = 'manager' LIMIT 1)
WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'michelle.ndungu@caavagroup.com');

-- HR
INSERT INTO users (email, password, name, role_id)
SELECT 'nancy.wambui@caavagroup.com', '$2a$10$rOzJqJqJqJqJqJqJqJqJeqJqJqJqJqJqJqJqJqJqJqJqJqJqJqJqJq', 'Nancy Wambui',
  (SELECT id FROM roles WHERE name = 'hr' LIMIT 1)
WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'nancy.wambui@caavagroup.com');

-- ============================================
-- DEPARTMENTS (UUIDs auto-generated by MySQL)
-- ============================================

INSERT INTO departments (name, description, manager_id) 
SELECT 'Software Development', 'Core development team working on Oracle-based insurance and banking solutions',
  (SELECT id FROM users WHERE email = 'michelle.ndungu@caavagroup.com' LIMIT 1)
WHERE NOT EXISTS (SELECT 1 FROM departments WHERE name = 'Software Development');

INSERT INTO departments (name, description, parent_id, manager_id)
SELECT 'Backend Development', 'Oracle Database, PL/SQL, and backend services development',
  (SELECT id FROM departments WHERE name = 'Software Development' LIMIT 1),
  (SELECT id FROM users WHERE email = 'jane.mwangi@caavagroup.com' LIMIT 1)
WHERE NOT EXISTS (SELECT 1 FROM departments WHERE name = 'Backend Development');

INSERT INTO departments (name, description, parent_id)
SELECT 'Frontend Development', 'Oracle ADF, JDeveloper, and user interface development',
  (SELECT id FROM departments WHERE name = 'Software Development' LIMIT 1)
WHERE NOT EXISTS (SELECT 1 FROM departments WHERE name = 'Frontend Development');

INSERT INTO departments (name, description)
SELECT 'Quality Assurance', 'QA and testing for insurance and banking software'
WHERE NOT EXISTS (SELECT 1 FROM departments WHERE name = 'Quality Assurance');

INSERT INTO departments (name, description)
SELECT 'Human Resources', 'HR and employee management'
WHERE NOT EXISTS (SELECT 1 FROM departments WHERE name = 'Human Resources');

INSERT INTO departments (name, description)
SELECT 'Operations', 'Day-to-day operations and client support'
WHERE NOT EXISTS (SELECT 1 FROM departments WHERE name = 'Operations');

-- ============================================
-- CATEGORIES (UUIDs auto-generated by MySQL)
-- ============================================

INSERT INTO categories (name, slug, description, icon, color) VALUES
('Onboarding', 'onboarding', 'New employee onboarding and orientation programs', 'UserPlus', '#10B981'),
('Oracle Database', 'oracle-database', 'Oracle Database administration and development', 'Database', '#F97316'),
('Oracle Tools', 'oracle-tools', 'Oracle development tools including Toad, JDeveloper, WebLogic', 'Wrench', '#3B82F6'),
('Insurance Fundamentals', 'insurance-fundamentals', 'Core insurance concepts and principles for Kenyan market', 'Shield', '#9333EA'),
('Banking & Finance', 'banking-finance', 'Banking operations and financial services training', 'DollarSign', '#10B981'),
('Regulatory Compliance', 'regulatory-compliance', 'Kenya regulatory requirements for insurance and banking', 'FileCheck', '#F59E0B'),
('Software Training', 'software-training', 'Training on insurance and banking software systems', 'Monitor', '#3B82F6'),
('Risk Management', 'risk-management', 'Risk assessment and management practices', 'AlertTriangle', '#EF4444'),
('Customer Service', 'customer-service', 'Customer relationship and service excellence', 'Users', '#8B5CF6'),
('Development Practices', 'development-practices', 'Software development methodologies and best practices', 'Code', '#6366F1')
ON DUPLICATE KEY UPDATE name=name;

-- ============================================
-- TAGS (UUIDs auto-generated by MySQL)
-- ============================================

INSERT INTO tags (name, slug) VALUES
('Oracle', 'oracle'),
('Toad', 'toad'),
('WebLogic', 'weblogic'),
('JDeveloper', 'jdeveloper'),
('Oracle Forms', 'oracle-forms'),
('Oracle ADF', 'oracle-adf'),
('PL/SQL', 'plsql'),
('Oracle Database', 'oracle-database'),
('Onboarding', 'onboarding'),
('New Hire', 'new-hire'),
('Insurance', 'insurance'),
('Banking', 'banking'),
('Compliance', 'compliance'),
('Kenya', 'kenya'),
('IRBA', 'irba'),
('CBK', 'cbk'),
('Software', 'software'),
('Risk', 'risk'),
('Claims', 'claims'),
('Underwriting', 'underwriting'),
('AML', 'aml'),
('KYC', 'kyc'),
('Development', 'development'),
('Testing', 'testing'),
('QA', 'qa')
ON DUPLICATE KEY UPDATE name=name;

-- ============================================
-- COURSES (Using MySQL UUID() and category/user lookups)
-- ============================================

-- ============================================
-- ONBOARDING COURSES
-- ============================================

INSERT INTO courses (title, slug, description, short_description, category_id, instructor_id, status, difficulty_level, duration_minutes, language, is_featured)
SELECT 
  'Welcome to CAAVA Group - New Employee Onboarding',
  'welcome-caava-group-onboarding',
  'Comprehensive onboarding program for new employees at CAAVA Group. Learn about our company culture, values, insurance and banking software solutions, Oracle technology stack, and your role in serving Kenyan financial institutions.',
  'Start your journey at CAAVA Group with our comprehensive onboarding program',
  (SELECT id FROM categories WHERE slug = 'onboarding' LIMIT 1),
  (SELECT id FROM users WHERE email = 'nancy.wambui@caavagroup.com' LIMIT 1),
  'published',
  'beginner',
  120,
  'en',
  TRUE
WHERE NOT EXISTS (SELECT 1 FROM courses WHERE slug = 'welcome-caava-group-onboarding');

INSERT INTO courses (title, slug, description, short_description, category_id, instructor_id, status, difficulty_level, duration_minutes, language, is_featured)
SELECT 
  'Company Policies & Procedures',
  'company-policies-procedures',
  'Essential company policies, procedures, and code of conduct for all CAAVA Group employees. Covers workplace policies, security protocols, and best practices.',
  'Learn essential company policies and procedures',
  (SELECT id FROM categories WHERE slug = 'onboarding' LIMIT 1),
  (SELECT id FROM users WHERE email = 'nancy.wambui@caavagroup.com' LIMIT 1),
  'published',
  'beginner',
  90,
  'en',
  TRUE
WHERE NOT EXISTS (SELECT 1 FROM courses WHERE slug = 'company-policies-procedures');

INSERT INTO courses (title, slug, description, short_description, category_id, instructor_id, status, difficulty_level, duration_minutes, language, is_featured)
SELECT 
  'Introduction to Our Insurance & Banking Solutions',
  'intro-insurance-banking-solutions',
  'Overview of CAAVA Group software solutions for insurance companies and banks in Kenya. Learn about the products we develop and maintain, client relationships, and industry context.',
  'Understand our software solutions for Kenyan insurance and banking sector',
  (SELECT id FROM categories WHERE slug = 'onboarding' LIMIT 1),
  (SELECT id FROM users WHERE email = 'jane.mwangi@caavagroup.com' LIMIT 1),
  'published',
  'beginner',
  150,
  'en',
  TRUE
WHERE NOT EXISTS (SELECT 1 FROM courses WHERE slug = 'intro-insurance-banking-solutions');

-- ============================================
-- ORACLE PRODUCTS COURSES
-- ============================================

INSERT INTO courses (title, slug, description, short_description, category_id, instructor_id, status, difficulty_level, duration_minutes, language, is_featured)
SELECT 
  'Oracle Toad for Database Administration',
  'oracle-toad-database-admin',
  'Comprehensive training on Oracle Toad for database administration and development. Learn to use Toad for querying, database management, performance tuning, and development tasks in our insurance and banking software projects.',
  'Master Oracle Toad for database administration and development',
  (SELECT id FROM categories WHERE slug = 'oracle-tools' LIMIT 1),
  (SELECT id FROM users WHERE email = 'david.ochieng@caavagroup.com' LIMIT 1),
  'published',
  'intermediate',
  300,
  'en',
  TRUE
WHERE NOT EXISTS (SELECT 1 FROM courses WHERE slug = 'oracle-toad-database-admin');

INSERT INTO courses (title, slug, description, short_description, category_id, instructor_id, status, difficulty_level, duration_minutes, language, is_featured)
SELECT 
  'Oracle WebLogic Server Administration',
  'oracle-weblogic-administration',
  'Learn to deploy, configure, and manage Oracle WebLogic Server for our Java-based insurance and banking applications. Covers domain configuration, cluster management, monitoring, and troubleshooting.',
  'Administer Oracle WebLogic Server for enterprise applications',
  (SELECT id FROM categories WHERE slug = 'oracle-tools' LIMIT 1),
  (SELECT id FROM users WHERE email = 'david.ochieng@caavagroup.com' LIMIT 1),
  'published',
  'advanced',
  360,
  'en',
  TRUE
WHERE NOT EXISTS (SELECT 1 FROM courses WHERE slug = 'oracle-weblogic-administration');

INSERT INTO courses (title, slug, description, short_description, category_id, instructor_id, status, difficulty_level, duration_minutes, language, is_featured)
SELECT 
  'Oracle JDeveloper for Application Development',
  'oracle-jdeveloper-development',
  'Build enterprise applications using Oracle JDeveloper. Learn ADF (Application Development Framework), creating UIs, business logic development, and deploying applications for insurance and banking solutions.',
  'Develop enterprise applications with Oracle JDeveloper and ADF',
  (SELECT id FROM categories WHERE slug = 'oracle-tools' LIMIT 1),
  (SELECT id FROM users WHERE email = 'sarah.akinyi@caavagroup.com' LIMIT 1),
  'published',
  'intermediate',
  420,
  'en',
  TRUE
WHERE NOT EXISTS (SELECT 1 FROM courses WHERE slug = 'oracle-jdeveloper-development');

INSERT INTO courses (title, slug, description, short_description, category_id, instructor_id, status, difficulty_level, duration_minutes, language, is_featured)
SELECT 
  'Oracle Forms Development',
  'oracle-forms-development',
  'Create and maintain Oracle Forms applications used in our legacy and modern insurance systems. Learn form design, triggers, data blocks, and integration with Oracle Database.',
  'Build and maintain Oracle Forms applications',
  (SELECT id FROM categories WHERE slug = 'oracle-tools' LIMIT 1),
  (SELECT id FROM users WHERE email = 'sarah.akinyi@caavagroup.com' LIMIT 1),
  'published',
  'intermediate',
  360,
  'en',
  FALSE
WHERE NOT EXISTS (SELECT 1 FROM courses WHERE slug = 'oracle-forms-development');

INSERT INTO courses (title, slug, description, short_description, category_id, instructor_id, status, difficulty_level, duration_minutes, language, is_featured)
SELECT 
  'Oracle Database Administration Fundamentals',
  'oracle-database-admin-fundamentals',
  'Essential Oracle Database administration skills for our development team. Learn database installation, configuration, user management, backup and recovery, and performance optimization for insurance and banking applications.',
  'Master Oracle Database administration fundamentals',
  (SELECT id FROM categories WHERE slug = 'oracle-database' LIMIT 1),
  (SELECT id FROM users WHERE email = 'david.ochieng@caavagroup.com' LIMIT 1),
  'published',
  'beginner',
  480,
  'en',
  TRUE
WHERE NOT EXISTS (SELECT 1 FROM courses WHERE slug = 'oracle-database-admin-fundamentals');

INSERT INTO courses (title, slug, description, short_description, category_id, instructor_id, status, difficulty_level, duration_minutes, language, is_featured)
SELECT 
  'PL/SQL Programming for Insurance Systems',
  'plsql-programming-insurance',
  'Learn PL/SQL programming specifically for insurance and banking software development. Covers stored procedures, functions, triggers, packages, and advanced PL/SQL features used in our Oracle-based solutions.',
  'Master PL/SQL programming for insurance and banking systems',
  (SELECT id FROM categories WHERE slug = 'oracle-database' LIMIT 1),
  (SELECT id FROM users WHERE email = 'jane.mwangi@caavagroup.com' LIMIT 1),
  'published',
  'intermediate',
  540,
  'en',
  TRUE
WHERE NOT EXISTS (SELECT 1 FROM courses WHERE slug = 'plsql-programming-insurance');

INSERT INTO courses (title, slug, description, short_description, category_id, instructor_id, status, difficulty_level, duration_minutes, language, is_featured)
SELECT 
  'Oracle ADF Application Development',
  'oracle-adf-application-development',
  'Build modern web applications using Oracle Application Development Framework (ADF). Learn ADF architecture, task flows, data binding, and creating responsive UIs for insurance and banking portals.',
  'Develop modern web applications with Oracle ADF',
  (SELECT id FROM categories WHERE slug = 'oracle-tools' LIMIT 1),
  (SELECT id FROM users WHERE email = 'sarah.akinyi@caavagroup.com' LIMIT 1),
  'published',
  'intermediate',
  480,
  'en',
  FALSE
WHERE NOT EXISTS (SELECT 1 FROM courses WHERE slug = 'oracle-adf-application-development');

-- ============================================
-- INSURANCE & BANKING COURSES
-- ============================================

INSERT INTO courses (title, slug, description, short_description, category_id, instructor_id, status, difficulty_level, duration_minutes, language, is_featured)
SELECT 
  'Introduction to Insurance in Kenya',
  'introduction-insurance-kenya',
  'Comprehensive introduction to the insurance industry in Kenya, covering regulatory framework, market structure, and key players. Learn about IRBA regulations, types of insurance products, and the role of insurance in the Kenyan economy.',
  'Learn the fundamentals of insurance in the Kenyan market',
  (SELECT id FROM categories WHERE slug = 'insurance-fundamentals' LIMIT 1),
  (SELECT id FROM users WHERE email = 'jane.mwangi@caavagroup.com' LIMIT 1),
  'published',
  'beginner',
  180,
  'en',
  TRUE
WHERE NOT EXISTS (SELECT 1 FROM courses WHERE slug = 'introduction-insurance-kenya');

INSERT INTO courses (title, slug, description, short_description, category_id, instructor_id, status, difficulty_level, duration_minutes, language, is_featured)
SELECT 
  'Banking Operations & CBK Regulations',
  'banking-operations-cbk',
  'Deep dive into banking operations in Kenya, Central Bank of Kenya (CBK) regulations, compliance requirements, and best practices for banking professionals.',
  'Master banking operations and CBK compliance requirements',
  (SELECT id FROM categories WHERE slug = 'banking-finance' LIMIT 1),
  (SELECT id FROM users WHERE email = 'jane.mwangi@caavagroup.com' LIMIT 1),
  'published',
  'intermediate',
  240,
  'en',
  TRUE
WHERE NOT EXISTS (SELECT 1 FROM courses WHERE slug = 'banking-operations-cbk');

INSERT INTO courses (title, slug, description, short_description, category_id, instructor_id, status, difficulty_level, duration_minutes, language, is_featured)
SELECT 
  'Anti-Money Laundering (AML) Compliance',
  'aml-compliance',
  'Comprehensive training on Anti-Money Laundering regulations in Kenya. Learn KYC procedures, suspicious transaction reporting, and compliance best practices for banks and insurance companies.',
  'Essential AML and KYC compliance training for financial institutions',
  (SELECT id FROM categories WHERE slug = 'regulatory-compliance' LIMIT 1),
  (SELECT id FROM users WHERE email = 'jane.mwangi@caavagroup.com' LIMIT 1),
  'published',
  'intermediate',
  120,
  'en',
  TRUE
WHERE NOT EXISTS (SELECT 1 FROM courses WHERE slug = 'aml-compliance');

INSERT INTO courses (title, slug, description, short_description, category_id, instructor_id, status, difficulty_level, duration_minutes, language, is_featured)
SELECT 
  'Insurance Claims Processing',
  'insurance-claims-processing',
  'Learn the end-to-end claims processing workflow in Kenyan insurance companies. Understand claim validation, assessment, approval workflows, and regulatory requirements.',
  'Master insurance claims processing workflows and procedures',
  (SELECT id FROM categories WHERE slug = 'insurance-fundamentals' LIMIT 1),
  (SELECT id FROM users WHERE email = 'david.ochieng@caavagroup.com' LIMIT 1),
  'published',
  'intermediate',
  180,
  'en',
  FALSE
WHERE NOT EXISTS (SELECT 1 FROM courses WHERE slug = 'insurance-claims-processing');

INSERT INTO courses (title, slug, description, short_description, category_id, instructor_id, status, difficulty_level, duration_minutes, language, is_featured)
SELECT 
  'Banking Core Systems Overview',
  'banking-core-systems-overview',
  'Introduction to core banking systems used in Kenya. Learn about account management, transaction processing, loan management, and integration points for our banking software solutions.',
  'Understand core banking systems and operations',
  (SELECT id FROM categories WHERE slug = 'banking-finance' LIMIT 1),
  (SELECT id FROM users WHERE email = 'david.ochieng@caavagroup.com' LIMIT 1),
  'published',
  'beginner',
  150,
  'en',
  FALSE
WHERE NOT EXISTS (SELECT 1 FROM courses WHERE slug = 'banking-core-systems-overview');

-- ============================================
-- DEVELOPMENT PRACTICES COURSES
-- ============================================

INSERT INTO courses (title, slug, description, short_description, category_id, instructor_id, status, difficulty_level, duration_minutes, language, is_featured)
SELECT 
  'Agile Development for Insurance & Banking Projects',
  'agile-development-insurance-banking',
  'Learn Agile methodologies tailored for insurance and banking software development. Covers Scrum, Kanban, sprint planning, and best practices for financial services projects.',
  'Apply Agile methodologies to financial services software development',
  (SELECT id FROM categories WHERE slug = 'development-practices' LIMIT 1),
  (SELECT id FROM users WHERE email = 'michelle.ndungu@caavagroup.com' LIMIT 1),
  'published',
  'intermediate',
  180,
  'en',
  FALSE
WHERE NOT EXISTS (SELECT 1 FROM courses WHERE slug = 'agile-development-insurance-banking');

INSERT INTO courses (title, slug, description, short_description, category_id, instructor_id, status, difficulty_level, duration_minutes, language, is_featured)
SELECT 
  'Testing Strategies for Financial Software',
  'testing-strategies-financial-software',
  'Comprehensive testing strategies for insurance and banking software. Learn unit testing, integration testing, security testing, and compliance testing for financial applications.',
  'Master testing strategies for financial software systems',
  (SELECT id FROM categories WHERE slug = 'development-practices' LIMIT 1),
  (SELECT id FROM users WHERE email = 'sarah.akinyi@caavagroup.com' LIMIT 1),
  'published',
  'intermediate',
  240,
  'en',
  FALSE
WHERE NOT EXISTS (SELECT 1 FROM courses WHERE slug = 'testing-strategies-financial-software');

-- ============================================
-- ENROLLMENTS - Sample enrollments for onboarding
-- ============================================

-- Enroll new users in onboarding courses
INSERT INTO enrollments (user_id, course_id, status)
SELECT 
  u.id,
  c.id,
  'enrolled'
FROM users u
CROSS JOIN courses c
WHERE u.email IN ('john.kamau@caavagroup.com', 'mary.wanjiku@caavagroup.com', 'peter.otieno@caavagroup.com')
  AND c.slug IN ('welcome-caava-group-onboarding', 'company-policies-procedures', 'intro-insurance-banking-solutions')
  AND NOT EXISTS (
    SELECT 1 FROM enrollments e 
    WHERE e.user_id = u.id AND e.course_id = c.id
  );

-- Enroll developers in Oracle courses
INSERT INTO enrollments (user_id, course_id, status)
SELECT 
  u.id,
  c.id,
  'enrolled'
FROM users u
CROSS JOIN courses c
WHERE u.email IN ('peter.otieno@caavagroup.com', 'james.kariuki@caavagroup.com')
  AND c.slug IN ('oracle-toad-database-admin', 'oracle-jdeveloper-development', 'oracle-database-admin-fundamentals', 'plsql-programming-insurance')
  AND NOT EXISTS (
    SELECT 1 FROM enrollments e 
    WHERE e.user_id = u.id AND e.course_id = c.id
  );

-- ============================================
-- USER DEPARTMENTS - Assign users to departments
-- ============================================

INSERT INTO user_departments (user_id, department_id, role)
SELECT u.id, d.id, 'manager'
FROM users u
CROSS JOIN departments d
WHERE u.email = 'michelle.ndungu@caavagroup.com'
  AND d.name = 'Software Development'
  AND NOT EXISTS (
    SELECT 1 FROM user_departments ud
    WHERE ud.user_id = u.id AND ud.department_id = d.id
  );

INSERT INTO user_departments (user_id, department_id, role)
SELECT u.id, d.id, 'team_lead'
FROM users u
CROSS JOIN departments d
WHERE u.email = 'jane.mwangi@caavagroup.com'
  AND d.name = 'Backend Development'
  AND NOT EXISTS (
    SELECT 1 FROM user_departments ud
    WHERE ud.user_id = u.id AND ud.department_id = d.id
  );

INSERT INTO user_departments (user_id, department_id, role)
SELECT u.id, d.id, 'member'
FROM users u
CROSS JOIN departments d
WHERE (u.email IN ('peter.otieno@caavagroup.com', 'james.kariuki@caavagroup.com') AND d.name = 'Backend Development')
   OR (u.email IN ('john.kamau@caavagroup.com', 'mary.wanjiku@caavagroup.com') AND d.name = 'Software Development')
   OR (u.email = 'nancy.wambui@caavagroup.com' AND d.name = 'Human Resources')
  AND NOT EXISTS (
    SELECT 1 FROM user_departments ud
    WHERE ud.user_id = u.id AND ud.department_id = d.id
  );

-- ============================================
-- COURSE TAGS - Link tags to courses
-- ============================================

-- Tag onboarding courses
INSERT INTO course_tags (course_id, tag_id)
SELECT c.id, t.id
FROM courses c
CROSS JOIN tags t
WHERE c.slug LIKE '%onboarding%'
  AND t.slug IN ('onboarding', 'new-hire')
  AND NOT EXISTS (
    SELECT 1 FROM course_tags ct
    WHERE ct.course_id = c.id AND ct.tag_id = t.id
  );

-- Tag Oracle courses
INSERT INTO course_tags (course_id, tag_id)
SELECT c.id, t.id
FROM courses c
CROSS JOIN tags t
WHERE (c.slug LIKE '%oracle%' OR c.slug LIKE '%toad%' OR c.slug LIKE '%weblogic%' OR c.slug LIKE '%jdeveloper%' OR c.slug LIKE '%plsql%')
  AND t.slug IN ('oracle', 'toad', 'weblogic', 'jdeveloper', 'oracle-database', 'plsql', 'development')
  AND NOT EXISTS (
    SELECT 1 FROM course_tags ct
    WHERE ct.course_id = c.id AND ct.tag_id = t.id
  )
LIMIT 50;

-- Tag insurance courses
INSERT INTO course_tags (course_id, tag_id)
SELECT c.id, t.id
FROM courses c
CROSS JOIN tags t
WHERE c.slug LIKE '%insurance%'
  AND t.slug IN ('insurance', 'kenya', 'irba', 'claims', 'underwriting')
  AND NOT EXISTS (
    SELECT 1 FROM course_tags ct
    WHERE ct.course_id = c.id AND ct.tag_id = t.id
  );

-- Tag banking courses
INSERT INTO course_tags (course_id, tag_id)
SELECT c.id, t.id
FROM courses c
CROSS JOIN tags t
WHERE c.slug LIKE '%banking%'
  AND t.slug IN ('banking', 'kenya', 'cbk', 'compliance', 'aml', 'kyc')
  AND NOT EXISTS (
    SELECT 1 FROM course_tags ct
    WHERE ct.course_id = c.id AND ct.tag_id = t.id
  );

-- ============================================
-- USER GROUPS - Create groups for different teams
-- ============================================

INSERT INTO user_groups (name, description, created_by)
SELECT 'New Employees 2025', 'Group for all new employees joining in 2025',
  (SELECT id FROM users WHERE email = 'nancy.wambui@caavagroup.com' LIMIT 1)
WHERE NOT EXISTS (SELECT 1 FROM user_groups WHERE name = 'New Employees 2025');

INSERT INTO user_groups (name, description, created_by)
SELECT 'Oracle Development Team', 'Team working on Oracle-based solutions',
  (SELECT id FROM users WHERE email = 'michelle.ndungu@caavagroup.com' LIMIT 1)
WHERE NOT EXISTS (SELECT 1 FROM user_groups WHERE name = 'Oracle Development Team');

INSERT INTO user_groups (name, description, created_by)
SELECT 'Insurance Software Team', 'Team focused on insurance software solutions',
  (SELECT id FROM users WHERE email = 'jane.mwangi@caavagroup.com' LIMIT 1)
WHERE NOT EXISTS (SELECT 1 FROM user_groups WHERE name = 'Insurance Software Team');

-- ============================================
-- USER GROUP MEMBERS - Add users to groups
-- ============================================

INSERT INTO user_group_members (user_id, group_id)
SELECT u.id, g.id
FROM users u
CROSS JOIN user_groups g
WHERE (u.email IN ('john.kamau@caavagroup.com', 'mary.wanjiku@caavagroup.com') AND g.name = 'New Employees 2025')
   OR (u.email IN ('peter.otieno@caavagroup.com', 'james.kariuki@caavagroup.com', 'jane.mwangi@caavagroup.com') AND g.name = 'Oracle Development Team')
   OR (u.email IN ('jane.mwangi@caavagroup.com', 'david.ochieng@caavagroup.com') AND g.name = 'Insurance Software Team')
  AND NOT EXISTS (
    SELECT 1 FROM user_group_members ugm
    WHERE ugm.user_id = u.id AND ugm.group_id = g.id
  );

-- ============================================
-- LEARNING PATHS - Create structured learning paths
-- ============================================

INSERT INTO learning_paths (title, description, category_id, status, is_featured, estimated_duration_hours, created_by)
SELECT 
  'New Employee Onboarding Path',
  'Complete onboarding journey for new CAAVA Group employees covering company culture, policies, and essential skills',
  (SELECT id FROM categories WHERE slug = 'onboarding' LIMIT 1),
  'published',
  TRUE,
  8,
  (SELECT id FROM users WHERE email = 'nancy.wambui@caavagroup.com' LIMIT 1)
WHERE NOT EXISTS (SELECT 1 FROM learning_paths WHERE title = 'New Employee Onboarding Path');

INSERT INTO learning_paths (title, description, category_id, status, is_featured, estimated_duration_hours, created_by)
SELECT 
  'Oracle Developer Certification Path',
  'Comprehensive path to become a certified Oracle developer at CAAVA Group, covering all essential Oracle tools and technologies',
  (SELECT id FROM categories WHERE slug = 'oracle-tools' LIMIT 1),
  'published',
  TRUE,
  40,
  (SELECT id FROM users WHERE email = 'david.ochieng@caavagroup.com' LIMIT 1)
WHERE NOT EXISTS (SELECT 1 FROM learning_paths WHERE title = 'Oracle Developer Certification Path');

INSERT INTO learning_paths (title, description, category_id, status, is_featured, estimated_duration_hours, created_by)
SELECT 
  'Insurance Industry Fundamentals',
  'Learn the fundamentals of insurance in Kenya and how our software solutions serve this industry',
  (SELECT id FROM categories WHERE slug = 'insurance-fundamentals' LIMIT 1),
  'published',
  FALSE,
  15,
  (SELECT id FROM users WHERE email = 'jane.mwangi@caavagroup.com' LIMIT 1)
WHERE NOT EXISTS (SELECT 1 FROM learning_paths WHERE title = 'Insurance Industry Fundamentals');

-- ============================================
-- LEARNING PATH COURSES - Add courses to learning paths
-- ============================================

-- Add courses to onboarding path
INSERT INTO learning_path_courses (learning_path_id, course_id, order_index, is_required)
SELECT lp.id, c.id, 
  CASE c.slug
    WHEN 'welcome-caava-group-onboarding' THEN 1
    WHEN 'company-policies-procedures' THEN 2
    WHEN 'intro-insurance-banking-solutions' THEN 3
    ELSE 4
  END,
  TRUE
FROM learning_paths lp
CROSS JOIN courses c
WHERE lp.title = 'New Employee Onboarding Path'
  AND c.slug IN ('welcome-caava-group-onboarding', 'company-policies-procedures', 'intro-insurance-banking-solutions')
  AND NOT EXISTS (
    SELECT 1 FROM learning_path_courses lpc
    WHERE lpc.learning_path_id = lp.id AND lpc.course_id = c.id
  );

-- Add courses to Oracle developer path
INSERT INTO learning_path_courses (learning_path_id, course_id, order_index, is_required)
SELECT lp.id, c.id,
  CASE c.slug
    WHEN 'oracle-database-admin-fundamentals' THEN 1
    WHEN 'oracle-toad-database-admin' THEN 2
    WHEN 'plsql-programming-insurance' THEN 3
    WHEN 'oracle-jdeveloper-development' THEN 4
    WHEN 'oracle-weblogic-administration' THEN 5
    ELSE 6
  END,
  TRUE
FROM learning_paths lp
CROSS JOIN courses c
WHERE lp.title = 'Oracle Developer Certification Path'
  AND c.slug IN ('oracle-database-admin-fundamentals', 'oracle-toad-database-admin', 'plsql-programming-insurance', 'oracle-jdeveloper-development', 'oracle-weblogic-administration')
  AND NOT EXISTS (
    SELECT 1 FROM learning_path_courses lpc
    WHERE lpc.learning_path_id = lp.id AND lpc.course_id = c.id
  );

-- ============================================
-- NOTIFICATIONS - Sample notifications
-- ============================================

INSERT INTO notifications (user_id, title, message, type, is_read)
SELECT 
  u.id,
  'Welcome to Knowledge Center!',
  'Your onboarding courses are ready. Start your learning journey with us.',
  'info',
  FALSE
FROM users u
WHERE u.email IN ('john.kamau@caavagroup.com', 'mary.wanjiku@caavagroup.com')
  AND NOT EXISTS (
    SELECT 1 FROM notifications n
    WHERE n.user_id = u.id AND n.title = 'Welcome to Knowledge Center!'
  );

INSERT INTO notifications (user_id, title, message, type, is_read)
SELECT 
  u.id,
  'New Course Available',
  'Oracle Toad for Database Administration course is now available for enrollment.',
  'course',
  FALSE
FROM users u
WHERE u.email IN ('peter.otieno@caavagroup.com', 'james.kariuki@caavagroup.com')
  AND NOT EXISTS (
    SELECT 1 FROM notifications n
    WHERE n.user_id = u.id AND n.title = 'New Course Available'
  );

-- ============================================
-- COMPLIANCE REQUIREMENTS - Mandatory training
-- ============================================

INSERT INTO compliance_requirements (title, description, course_id, required_for, deadline_days, is_mandatory, priority)
SELECT 
  'New Employee Onboarding - Mandatory',
  'All new employees must complete onboarding within first 30 days',
  (SELECT id FROM courses WHERE slug = 'welcome-caava-group-onboarding' LIMIT 1),
  'all',
  30,
  TRUE,
  'high'
WHERE NOT EXISTS (
  SELECT 1 FROM compliance_requirements cr
  WHERE cr.title = 'New Employee Onboarding - Mandatory'
);

INSERT INTO compliance_requirements (title, description, course_id, required_for, deadline_days, is_mandatory, priority)
SELECT 
  'Company Policies Training - Mandatory',
  'All employees must complete company policies training annually',
  (SELECT id FROM courses WHERE slug = 'company-policies-procedures' LIMIT 1),
  'all',
  365,
  TRUE,
  'high'
WHERE NOT EXISTS (
  SELECT 1 FROM compliance_requirements cr
  WHERE cr.title = 'Company Policies Training - Mandatory'
);

-- ============================================
-- BADGES - Gamification badges
-- ============================================

INSERT INTO badges (name, description, criteria)
VALUES
('First Steps', 'Completed your first course', 'Complete any course'),
('Oracle Certified', 'Completed Oracle Developer Certification Path', 'Complete Oracle Developer Certification Path'),
('Onboarding Complete', 'Finished new employee onboarding', 'Complete all onboarding courses'),
('Insurance Expert', 'Completed 5 insurance-related courses', 'Complete 5 insurance courses'),
('Banking Professional', 'Completed 5 banking-related courses', 'Complete 5 banking courses'),
('Oracle Master', 'Mastered all Oracle tools and technologies', 'Complete all Oracle tool courses'),
('Dedicated Learner', 'Completed 10 courses', 'Complete 10 courses'),
('Knowledge Seeker', 'Completed 20 courses', 'Complete 20 courses')
ON DUPLICATE KEY UPDATE name=name;

-- ============================================
-- USER POINTS - Initialize points for users
-- ============================================

INSERT INTO user_points (user_id, total_points, current_level, points_this_month)
SELECT id, 0, 1, 0
FROM users
WHERE NOT EXISTS (
  SELECT 1 FROM user_points up
  WHERE up.user_id = users.id
);
