-- Sample Data for Knowledge Center LMS
-- UUIDs are automatically generated by MySQL using DEFAULT (uuid())
-- When inserting, simply omit the 'id' field and MySQL will generate it automatically

-- ============================================
-- ROLES (UUIDs auto-generated by MySQL)
-- ============================================

-- Insert default roles (UUIDs will be auto-generated)
INSERT INTO roles (name, display_name, description, is_system_role) VALUES
('admin', 'Administrator', 'Full system access with all permissions', TRUE),
('learner', 'Learner', 'Standard user with access to learning content', TRUE),
('instructor', 'Instructor', 'Can create and manage courses', TRUE),
('auditor', 'Auditor', 'Read-only access for auditing purposes', TRUE)
ON DUPLICATE KEY UPDATE name=name;

-- ============================================
-- SAMPLE USERS (UUIDs auto-generated by MySQL)
-- ============================================

-- Insert sample users with role lookups (UUIDs will be auto-generated)
INSERT INTO users (email, password, name, role_id)
SELECT 
  'admin@caavagroup.com',
  '$2a$10$rOzJqJqJqJqJqJqJqJqJeqJqJqJqJqJqJqJqJqJqJqJqJqJqJqJqJq',
  'Admin User',
  (SELECT id FROM roles WHERE name = 'admin' LIMIT 1)
WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'admin@caavagroup.com');

INSERT INTO users (email, password, name, role_id)
SELECT 
  'learner@caavagroup.com',
  '$2a$10$rOzJqJqJqJqJqJqJqJqJeqJqJqJqJqJqJqJqJqJqJqJqJqJqJqJqJq',
  'John Kamau',
  (SELECT id FROM roles WHERE name = 'learner' LIMIT 1)
WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'learner@caavagroup.com');

INSERT INTO users (email, password, name, role_id)
SELECT 
  'instructor@caavagroup.com',
  '$2a$10$rOzJqJqJqJqJqJqJqJqJeqJqJqJqJqJqJqJqJqJqJqJqJqJqJqJqJq',
  'Jane Mwangi',
  (SELECT id FROM roles WHERE name = 'instructor' LIMIT 1)
WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'instructor@caavagroup.com');

INSERT INTO users (email, password, name, role_id)
SELECT 
  'peter.otieno@caavagroup.com',
  '$2a$10$rOzJqJqJqJqJqJqJqJqJeqJqJqJqJqJqJqJqJqJqJqJqJqJqJqJqJq',
  'Peter Otieno',
  (SELECT id FROM roles WHERE name = 'learner' LIMIT 1)
WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'peter.otieno@caavagroup.com');

INSERT INTO users (email, password, name, role_id)
SELECT 
  'mary.wanjiku@caavagroup.com',
  '$2a$10$rOzJqJqJqJqJqJqJqJqJeqJqJqJqJqJqJqJqJqJqJqJqJqJqJqJqJq',
  'Mary Wanjiku',
  (SELECT id FROM roles WHERE name = 'learner' LIMIT 1)
WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'mary.wanjiku@caavagroup.com');

-- ============================================
-- CATEGORIES (UUIDs auto-generated by MySQL)
-- ============================================

INSERT INTO categories (name, slug, description, icon, color) VALUES
('Insurance Fundamentals', 'insurance-fundamentals', 'Core insurance concepts and principles for Kenyan market', 'Shield', '#9333EA'),
('Banking & Finance', 'banking-finance', 'Banking operations and financial services training', 'DollarSign', '#10B981'),
('Regulatory Compliance', 'regulatory-compliance', 'Kenya regulatory requirements for insurance and banking', 'FileCheck', '#F59E0B'),
('Software Training', 'software-training', 'Training on insurance and banking software systems', 'Monitor', '#3B82F6'),
('Risk Management', 'risk-management', 'Risk assessment and management practices', 'AlertTriangle', '#EF4444'),
('Customer Service', 'customer-service', 'Customer relationship and service excellence', 'Users', '#8B5CF6')
ON DUPLICATE KEY UPDATE name=name;

-- ============================================
-- TAGS (UUIDs auto-generated by MySQL)
-- ============================================

INSERT INTO tags (name, slug) VALUES
('Insurance', 'insurance'),
('Banking', 'banking'),
('Compliance', 'compliance'),
('Kenya', 'kenya'),
('IRBA', 'irba'),
('CBK', 'cbk'),
('Software', 'software'),
('Risk', 'risk'),
('Claims', 'claims'),
('Underwriting', 'underwriting'),
('AML', 'aml'),
('KYC', 'kyc')
ON DUPLICATE KEY UPDATE name=name;

-- ============================================
-- COURSES (Using MySQL UUID() and category/user lookups)
-- ============================================

-- Course 1: Introduction to Insurance
INSERT INTO courses (title, slug, description, short_description, category_id, instructor_id, status, difficulty_level, duration_minutes, price, currency, language, is_featured)
SELECT 
  'Introduction to Insurance in Kenya',
  'introduction-insurance-kenya',
  'Comprehensive introduction to the insurance industry in Kenya, covering regulatory framework, market structure, and key players. Learn about IRBA regulations, types of insurance products, and the role of insurance in the Kenyan economy.',
  'Learn the fundamentals of insurance in the Kenyan market',
  (SELECT id FROM categories WHERE slug = 'insurance-fundamentals' LIMIT 1),
  (SELECT id FROM users WHERE email = 'instructor@caavagroup.com' LIMIT 1),
  'published',
  'beginner',
  180,
  0.00,
  'KES',
  'en',
  TRUE
WHERE NOT EXISTS (SELECT 1 FROM courses WHERE slug = 'introduction-insurance-kenya');

-- Course 2: Banking Operations
INSERT INTO courses (title, slug, description, short_description, category_id, instructor_id, status, difficulty_level, duration_minutes, price, currency, language, is_featured)
SELECT 
  'Banking Operations & CBK Regulations',
  'banking-operations-cbk',
  'Deep dive into banking operations in Kenya, Central Bank of Kenya (CBK) regulations, compliance requirements, and best practices for banking professionals.',
  'Master banking operations and CBK compliance requirements',
  (SELECT id FROM categories WHERE slug = 'banking-finance' LIMIT 1),
  (SELECT id FROM users WHERE email = 'instructor@caavagroup.com' LIMIT 1),
  'published',
  'intermediate',
  240,
  0.00,
  'KES',
  'en',
  TRUE
WHERE NOT EXISTS (SELECT 1 FROM courses WHERE slug = 'banking-operations-cbk');

-- Course 3: Insurance Software
INSERT INTO courses (title, slug, description, short_description, category_id, instructor_id, status, difficulty_level, duration_minutes, price, currency, language, is_featured)
SELECT 
  'Insurance Software Systems Training',
  'insurance-software-systems',
  'Hands-on training on insurance management software systems used in Kenya. Learn to navigate policy management, claims processing, and reporting modules.',
  'Master insurance software systems used in Kenyan insurance companies',
  (SELECT id FROM categories WHERE slug = 'software-training' LIMIT 1),
  (SELECT id FROM users WHERE email = 'instructor@caavagroup.com' LIMIT 1),
  'published',
  'beginner',
  300,
  0.00,
  'KES',
  'en',
  FALSE
WHERE NOT EXISTS (SELECT 1 FROM courses WHERE slug = 'insurance-software-systems');

-- Course 4: AML Compliance
INSERT INTO courses (title, slug, description, short_description, category_id, instructor_id, status, difficulty_level, duration_minutes, price, currency, language, is_featured)
SELECT 
  'Anti-Money Laundering (AML) Compliance',
  'aml-compliance',
  'Comprehensive training on Anti-Money Laundering regulations in Kenya. Learn KYC procedures, suspicious transaction reporting, and compliance best practices for banks and insurance companies.',
  'Essential AML and KYC compliance training for financial institutions',
  (SELECT id FROM categories WHERE slug = 'regulatory-compliance' LIMIT 1),
  (SELECT id FROM users WHERE email = 'instructor@caavagroup.com' LIMIT 1),
  'published',
  'intermediate',
  120,
  0.00,
  'KES',
  'en',
  TRUE
WHERE NOT EXISTS (SELECT 1 FROM courses WHERE slug = 'aml-compliance');
