/**
 * Generate a UUID v4 (36 characters with dashes)
 * Format matches MySQL's uuid() function output
 * Note: UUIDs are auto-generated by MySQL using DEFAULT (uuid())
 * This utility is only needed if you want to generate UUIDs in JavaScript code
 */
export const generateUUID = () => {
  // Generate standard UUID v4 with dashes
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
    const r = Math.random() * 16 | 0;
    const v = c === 'x' ? r : (r & 0x3 | 0x8);
    return v.toString(16);
  });
};

/**
 * Validate UUID format (36 characters with dashes)
 * Format: 8-4-4-4-12 hex characters
 */
export const isValidUUID = (uuid) => {
  return /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(uuid);
};

/**
 * Remove dashes from UUID (if needed for comparison)
 */
export const removeDashes = (uuid) => {
  return uuid ? uuid.replace(/-/g, '') : uuid;
};
